[package]
name = "edxlc"
version = "1.0.0"
authors = ["Andrew Smith"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
hotwatch = "0.4.5"
